import { Typography } from '@mui/material';
import Head from 'next/head';

import Layout from '@/src/components/layout';

export default function PackingsPage() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Packings</Typography>
    </Layout>
  );
}
