import {
  Button,
  Card,
  CardActions,
  CardContent,
  Stack,
  Typography
} from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Layout from '@/src/components/layout';

export default function HomePage() {
  const router = useRouter();

  return (
    <Layout>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography variant="h4" gutterBottom>
          Resumen
        </Typography>
        <Typography variant="body1" gutterBottom>
          En esta sección se muestra un resumen de la información de la empresa.
        </Typography>
        <Stack
          direction={{ xs: 'column', sm: 'row' }}
          alignItems="center"
          my={3}
          gap={3}
        >
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Administración de secuencias
              </Typography>
              <Typography variant="body1" gutterBottom>
                En este apartado se encuentran un listado de las secuencias
              </Typography>
            </CardContent>
            <CardActions>
              <Button
                fullWidth
                color="primary"
                onClick={() => router.push('/sequences')}
              >
                Ver listado
              </Button>
            </CardActions>
          </Card>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Administración de usuarios
              </Typography>
              <Typography variant="body1" gutterBottom>
                En este apartado se encuentran un listado de los usuarios
              </Typography>
            </CardContent>
            <CardActions>
              <Button
                fullWidth
                color="primary"
                onClick={() => router.push('/users')}
              >
                Ver listado
              </Button>
            </CardActions>
          </Card>
        </Stack>
      </main>
    </Layout>
  );
}
