import { useCallback, useEffect, useState } from 'react';
import { FilePond, registerPlugin } from 'react-filepond';
import toast from 'react-hot-toast';
import { useQuery } from 'react-query';
import {
  Delete as DeleteIcon,
  GetApp as DownloadIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon
} from '@mui/icons-material';
import {
  Box,
  Button,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  FormControl,
  IconButton,
  InputAdornment,
  InputLabel,
  OutlinedInput,
  Stack,
  Typography
} from '@mui/material';
import axios from 'axios';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

import Layout from '@/src/components/layout';
import WeekTabs from '@/src/components/tabs';
import { groupArray } from '@/src/utils/data';

import 'filepond/dist/filepond.min.css';

registerPlugin(FilePondPluginFileValidateType);
export default function SequencesPage() {
  const [files, setFiles] = useState<any[]>([]);
  const [openDialog, setOpenDialog] = useState(false);
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [userHasVerified, setUserHasVerified] = useState(false);
  const [rows, setRows] = useState<any[]>([]);

  const { data: client } = useSession();
  const { isLoading, error, data, refetch } = useQuery(
    'inventories',
    () =>
      fetch('/api/sequences/list', {
        method: 'GET',
        headers: {
          id: client?.user.id as string
        }
      }).then(res => res.json()),
    {
      enabled: !!client?.user.id
    }
  );

  const handleExport = () => {
    toast.loading('Descargando reporte...');
    axios('/api/sequences/export', {
      responseType: 'blob',
      headers: {
        id: client?.user.id as string
      }
    })
      .then(res => {
        const file = window.URL.createObjectURL(res.data);
        window.location.assign(file);
        toast.dismiss();
        toast.success('Reporte descargado');
      })
      .catch(() => toast.error('Ha ocurrido un error al descargar el reporte'));
  };

  const handleDrop = () => {
    handleDialog();
    axios('/api/users/verify', {
      headers: {
        id: client?.user.id as string,
        password: password
      }
    })
      .then(() => {
        toast.success('Usuario verificado');
        setUserHasVerified(true);
      })
      .catch(() => {
        toast.error('Contraseña incorrecta');
        setUserHasVerified(false);
      })
      .finally(() => {
        setPassword('');
      });
  };

  const handleRefresh = useCallback(() => {
    refetch();
  }, [refetch]);

  const handleDialog = useCallback(() => {
    setOpenDialog(!openDialog);
  }, [openDialog]);

  useEffect(() => {
    if (userHasVerified) {
      toast.loading('Limpiando listado...');
      axios('/api/sequences/truncate', {
        headers: {
          id: client?.user.id as string,
          password: password
        }
      })
        .then(() => {
          toast.success('Listado limpiado');
        })
        .catch(() => {
          toast.error('Ha ocurrido un error al limpiar el listado');
        })
        .finally(() => {
          setRows([]);
          setUserHasVerified(false);
          toast.dismiss();
          refetch();
        });
    }
  }, [client?.user.id, handleDialog, password, refetch, userHasVerified]);

  useEffect(() => {
    if (!isLoading && data?.stack?.length > 0) {
      const rows = groupArray(data.stack, 'week');
      const titleRows = Object.keys(rows);
      const entriesRows = Object.values(rows);
      const newRows = entriesRows.map((entry: any, index) => {
        return {
          id: index,
          week: titleRows[index],
          updateAt: entry[0].updatedAt,
          stack: entry.map((item: any, index: number) => ({
            id: item.id,
            partNumber: item.partNumber,
            buildSequence: item.buildSequence,
            quantity: item.quantity,
            poNo: item.poNo,
            vendorNo: item.vendorNo,
            packingDiskNo: item.packingDiskNo,
            line: item.line,
            scannedBy: item.scannedBy
          }))
        };
      });
      const sortedRows = newRows.sort((a, b) => {
        return a.week > b.week ? 1 : -1;
      });
      setRows(sortedRows);
    }
  }, [data, isLoading]);

  return (
    <Layout>
      <Head>
        <title>Secuencias</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h4" gutterBottom>
        Secuencias
      </Typography>
      <Typography variant="body1" gutterBottom>
        En esta sección podrás ver el listado de secuencias que se han
        escaneado.
      </Typography>
      <Stack
        direction={{ xs: 'column', sm: 'row' }}
        justifyContent="space-between"
        my={3}
      >
        <Typography variant="h5" gutterBottom fontWeight="400" textAlign="left">
          Total de secuencias: {data?.stack?.length || 0}
        </Typography>
        <Stack direction={{ xs: 'column', sm: 'row' }} gap={2}>
          <Button
            variant="outlined"
            endIcon={<DownloadIcon />}
            disabled={isLoading || !data?.stack?.length}
            onClick={handleExport}
          >
            Descargar reporte
          </Button>
          <Button
            variant="outlined"
            color="error"
            startIcon={<DeleteIcon />}
            disabled={isLoading || !data?.stack?.length}
            onClick={handleDialog}
          >
            Limpiar listado general
          </Button>
        </Stack>
      </Stack>
      <Box my={3}>
        <FilePond
          dropOnPage
          files={files}
          onupdatefiles={setFiles}
          allowMultiple={false}
          maxFiles={1}
          disabled={isLoading}
          acceptedFileTypes={['application/vnd.ms-excel', 'text/csv', '.csv']}
          name="files"
          labelIdle='Arrastra y suelta tu archivo o <span class="filepond--label-action">buscar</span>'
          server={{
            url: '/api/sequences/import',
            headers: {
              id: client?.user.id as string
            }
          }}
          onprocessfile={(err, _) => {
            if (err) {
              toast.error('Ha ocurrido un error al importar el archivo');
            } else {
              toast.success('Archivo importado');
              refetch();
            }
          }}
        />
      </Box>
      {isLoading && (
        <Stack gap={2}>
          <Typography variant="h5" gutterBottom>
            Cargando datos...
          </Typography>
          <CircularProgress color="secondary" />
        </Stack>
      )}
      {!isLoading && Boolean(error) && (
        <Stack>
          <Typography>
            Ha ocurrido un error al cargar los datos, por favor intenta de
            nuevo.
          </Typography>
        </Stack>
      )}
      {!isLoading && <WeekTabs data={rows} onRefresh={handleRefresh} />}
      <Dialog open={openDialog} onClose={handleDialog}>
        <DialogTitle>Mensaje</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Para poder eliminar el listado de secuencias, por favor ingresa tu
            contraseña.
          </DialogContentText>
          <FormControl fullWidth focused variant="outlined" sx={{ mt: 3 }}>
            <InputLabel htmlFor="outlined-adornment-password">
              Contraseña
            </InputLabel>
            <OutlinedInput
              autoFocus
              fullWidth
              margin="dense"
              label="Contraseña"
              value={password}
              onChange={e => setPassword(e.target.value)}
              id="outlined-adornment-password"
              type={showPassword ? 'text' : 'password'}
              endAdornment={
                <InputAdornment position="end">
                  <IconButton
                    aria-label="toggle password visibility"
                    onClick={() => setShowPassword(!showPassword)}
                    onMouseDown={e => e.preventDefault()}
                    edge="end"
                  >
                    {showPassword ? <VisibilityOffIcon /> : <VisibilityIcon />}
                  </IconButton>
                </InputAdornment>
              }
            />
          </FormControl>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleDialog}>Cancelar</Button>
          <Button
            color="error"
            onClick={handleDrop}
            disabled={!password.length}
          >
            Confirmar
          </Button>
        </DialogActions>
      </Dialog>
    </Layout>
  );
}